# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestGroupAdd:
    def setup_method(self, method):
        self.wd = webdriver.Firefox()

    def teardown_method(self, method):
        self.wd.quit()

    def test_group_add(self):
        self.wd.get("http://localhost/addressbook/")
        self.wd.find_element(By.NAME, "user").send_keys("admin")
        self.wd.find_element(By.NAME, "pass").send_keys("secret")
        self.wd.find_element(By.NAME, "pass").send_keys(Keys.ENTER)
        WebDriverWait(self.wd, 5).until(ec.visibility_of_element_located((By.ID, "footer")))
        self.wd.find_element(By.LINK_TEXT, "groups").click()
        WebDriverWait(self.wd, 5).until(ec.visibility_of_element_located((By.ID, "footer")))
        self.wd.find_element(By.NAME, "new").click()
        WebDriverWait(self.wd, 5).until(ec.visibility_of_element_located((By.ID, "footer")))
        self.wd.find_element(By.NAME, "group_name").click()
        self.wd.find_element(By.NAME, "group_name").send_keys("123")
        self.wd.find_element(By.NAME, "group_header").click()
        self.wd.find_element(By.NAME, "group_header").send_keys("456")
        self.wd.find_element(By.NAME, "group_footer").click()
        self.wd.find_element(By.NAME, "group_footer").send_keys("abc")
        self.wd.find_element(By.NAME, "submit").click()
        WebDriverWait(self.wd, 5).until(ec.visibility_of_element_located((By.ID, "footer")))
        self.wd.find_element(By.LINK_TEXT, "group page").click()
        self.wd.find_element(By.LINK_TEXT, "Logout").click()
