# Generated by Selenium IDE
from selenium import webdriver
from model.group import Group


class TestGroupAdd:
    def setup_method(self, method):
        self.wd = webdriver.Firefox()

    def teardown_method(self, method):
        self.wd.quit()

    def test_group_add(self):
        self.open_home_page()
        self.login(username="admin", password="secret")
        self.open_groups_page()
        self.init_group_creation()
        group = Group(name="123", header="456", footer="abc")
        self.fill_group_form(group)
        self.submit_group_creation()
        self.return_to_group_page()
        self.logout()

    def test_empty_group_add(self):
        group = Group(name="", header="", footer="")
        self.open_home_page()
        self.login(username="admin", password="secret")
        self.open_groups_page()
        self.init_group_creation()
        self.fill_group_form(group)
        self.submit_group_creation()
        self.return_to_group_page()
        self.logout()


